version: '3.8'
services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=a123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: